function M = beam_coefficientmatrix(a,l,lam)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(A,L,LAM)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:49

t2 = lam.^2;
t3 = t2.*2.0;
t4 = lam.*t2.*2.0;
t5 = a-l;
t6 = lam.*t5;
t7 = cos(t6);
t8 = exp(t6);
t9 = sin(t6);
t10 = exp(-t6);
t11 = lam.*t7.*t10;
t12 = lam.*t9.*t10;
t13 = lam.*t8.*t9;
t14 = lam.*t2.*t9.*t10.*2.0;
t15 = lam.*t2.*t7.*t8.*2.0;
t16 = lam.*t2.*t8.*t9.*2.0;
M = reshape([0.0,lam.*t2.*-2.0,t7.*exp(-lam.*t5),t11+t12,t2.*t9.*t10.*2.0,t14-lam.*t2.*t7.*t10.*2.0,0.0,0.0,t3,t4,-t9.*t10,t11-t12,t2.*t7.*t10.*2.0,t14+lam.*t2.*t7.*t10.*2.0,0.0,0.0,0.0,t4,t7.*t8,t13-lam.*t7.*t8,t2.*t8.*t9.*-2.0,t15+t16,0.0,0.0,-t3,t4,-t8.*t9,t13+lam.*t7.*t8,t2.*t7.*t8.*-2.0,t15-t16,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.0,a.*6.0,6.0],[8,8]);
