function U = displacement(x,EA,a,kt,l,mu,qt,z1,z2,z3,z4)
%DISPLACEMENT
%    U = DISPLACEMENT(X,EA,A,KT,L,MU,QT,Z1,Z2,Z3,Z4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:51

if ((a+x <= l) & (0.0 <= x))
    U = z1.*cosh(mu.*x)+z2.*sinh(mu.*x)+qt./kt;
elseif ((l < a+x) & (x <= l))
    U = z3+z4.*(a-l+x)-(qt.*(a-l+x).^2.*(1.0./2.0))./EA;
else
    U = 0.0;
end
