function M = beam_coefficientmatrix(EI,kGA,kn,ks,l1,l4,lam1,lam2)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(EI,KGA,KN,KS,L1,L4,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2019 11:05:51

t2 = lam1.^2;
t3 = 1.0./kGA;
t4 = 1.0./kGA.^2;
t5 = EI.*kn.*t4;
t6 = t5-1.0;
t7 = lam2.^2;
t8 = ks.*t3;
t9 = t8+1.0;
t10 = l1.*lam1;
t11 = l1.*lam2;
t12 = sinh(t10);
t13 = cosh(t10);
t14 = sinh(t11);
t15 = cosh(t11);
t16 = lam1.*t6;
t17 = lam2.*t6;
t18 = t2.^2;
t19 = t7.^2;
t20 = t2.*t6;
t21 = t6.*t7;
t22 = l4.*lam1;
t23 = cosh(t22);
t24 = sinh(t22);
t25 = l4.*lam2;
t26 = cosh(t25);
t27 = sinh(t25);
M = reshape([t20-EI.*t3.*t9.*t18,0.0,t13,lam1.*t6.*t12-EI.*lam1.*t2.*t3.*t9.*t12,t2.*t6.*t13-EI.*t3.*t9.*t13.*t18,lam1.*t12,0.0,0.0,0.0,lam1+t16-EI.*lam1.*t2.*t3.*t9,t12,lam1.*t6.*t13-EI.*lam1.*t2.*t3.*t9.*t13,t2.*t6.*t12-EI.*t3.*t9.*t12.*t18,lam1.*t13,0.0,0.0,t21-EI.*t3.*t9.*t19,0.0,t15,lam2.*t6.*t14-EI.*lam2.*t3.*t7.*t9.*t14,t6.*t7.*t15-EI.*t3.*t9.*t15.*t19,lam2.*t14,0.0,0.0,0.0,lam2+t17-EI.*lam2.*t3.*t7.*t9,t14,lam2.*t6.*t15-EI.*lam2.*t3.*t7.*t9.*t15,t6.*t7.*t14-EI.*t3.*t9.*t14.*t19,lam2.*t15,0.0,0.0,0.0,0.0,-1.0,0.0,-t20+EI.*t3.*t9.*t18,0.0,t2.*t6.*t23-EI.*t3.*t9.*t18.*t23,lam1.*t24+lam1.*t6.*t24-EI.*lam1.*t2.*t3.*t9.*t24,0.0,0.0,0.0,-t16+EI.*lam1.*t2.*t3.*t9,0.0,-lam1,t2.*t6.*t24-EI.*t3.*t9.*t18.*t24,lam1.*t23+lam1.*t6.*t23-EI.*lam1.*t2.*t3.*t9.*t23,0.0,0.0,-1.0,0.0,-t21+EI.*t3.*t9.*t19,0.0,t6.*t7.*t26-EI.*t3.*t9.*t19.*t26,lam2.*t27+lam2.*t6.*t27-EI.*lam2.*t3.*t7.*t9.*t27,0.0,0.0,0.0,-t17+EI.*lam2.*t3.*t7.*t9,0.0,-lam2,t6.*t7.*t27-EI.*t3.*t9.*t19.*t27,lam2.*t26+lam2.*t6.*t26-EI.*lam2.*t3.*t7.*t9.*t26],[8,8]);
