function Wp = inclination(x,c1,c2,c3,c4,c13,c14,c15,c16,l,l1,lam1,lam2)
%INCLINATION
%    WP = INCLINATION(X,C1,C2,C3,C4,C13,C14,C15,C16,L,L1,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2019 11:05:52

if ((x <= l1) & (0.0 <= x))
    Wp = c2.*lam1.*cosh(lam1.*x)+c4.*lam2.*cosh(lam2.*x)+c1.*lam1.*sinh(lam1.*x)+c3.*lam2.*sinh(lam2.*x);
elseif ((l1 < x) & (x <= l))
    Wp = c14.*lam1.*cosh(lam1.*(l1-x))+c16.*lam2.*cosh(lam2.*(l1-x))-c13.*lam1.*sinh(lam1.*(l1-x))-c15.*lam2.*sinh(lam2.*(l1-x));
else
    Wp = 0.0;
end
