function U = displacement(x,EA,kt,l,l1,l2,l3,mu,qt,z1,z2,z3,z4,z5,z6,z7,z8)
%DISPLACEMENT
%    U = DISPLACEMENT(X,EA,KT,L,L1,L2,L3,MU,QT,Z1,Z2,Z3,Z4,Z5,Z6,Z7,Z8)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:50

if ((x <= l1) & (0.0 <= x))
    U = z1.*cosh(mu.*x)+z2.*sinh(mu.*x)+qt./kt;
elseif ((x <= l1+l2) & (l1 < x))
    U = z3-z4.*(l1-x)-(qt.*(l1-x).^2.*(1.0./2.0))./EA;
elseif ((l1+l2 < x) & (x <= l1+l2+l3))
    U = z5-z6.*(l1+l2-x)-(qt.*(l1+l2-x).^2.*(1.0./2.0))./EA;
elseif ((x <= l) & (l1+l2+l3 < x))
    U = z7.*cosh(mu.*(l1+l2+l3-x))-z8.*sinh(mu.*(l1+l2+l3-x))+qt./kt;
else
    U = 0.0;
end
