function C = rod_coefficientmatrix(l1,l2,l3,l4,mu)
%ROD_COEFFICIENTMATRIX
%    C = ROD_COEFFICIENTMATRIX(L1,L2,L3,L4,MU)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:50

t2 = l1.*mu;
t3 = sinh(t2);
t4 = cosh(t2);
t5 = l4.*mu;
C = reshape([0.0,t4,mu.*t3,0.0,0.0,0.0,0.0,0.0,mu,t3,mu.*t4,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,l2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,l3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,mu.*sinh(t5),0.0,0.0,0.0,0.0,0.0,0.0,-mu,mu.*cosh(t5)],[8,8]);
