function d = rod_righthandsidevector(EA,Ft,kt,l2,l3,qt)
%ROD_RIGHTHANDSIDEVECTOR
%    D = ROD_RIGHTHANDSIDEVECTOR(EA,FT,KT,L2,L3,QT)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:50

t2 = 1.0./EA;
t3 = 1.0./kt;
d = [0.0;-qt.*t3;0.0;l2.^2.*qt.*t2.*(1.0./2.0);Ft.*t2+l2.*qt.*t2;qt.*t3+l3.^2.*qt.*t2.*(1.0./2.0);l3.*qt.*t2;0.0];
