function M = beam_coefficientmatrix(EI,kGA,kn,l1,l4,lam1,lam2)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(EI,KGA,KN,L1,L4,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Feb-2019 15:25:07

t2 = lam1.^2;
t3 = 1.0./kGA.^2;
t4 = EI.*kn.*t3;
t5 = t4-1.0;
t6 = 1.0./kGA;
t7 = lam2.^2;
t8 = l1.*lam1;
t9 = l1.*lam2;
t10 = sinh(t8);
t11 = cosh(t8);
t12 = sinh(t9);
t13 = cosh(t9);
t14 = lam1.*t5;
t15 = lam2.*t5;
t16 = t2.^2;
t17 = t7.^2;
t18 = t2.*t5;
t19 = t5.*t7;
t20 = l4.*lam1;
t21 = cosh(t20);
t22 = sinh(t20);
t23 = l4.*lam2;
t24 = cosh(t23);
t25 = sinh(t23);
M = reshape([t18-EI.*t6.*t16,0.0,t11,lam1.*t5.*t10-EI.*lam1.*t2.*t6.*t10,t2.*t5.*t11-EI.*t6.*t11.*t16,lam1.*t10,0.0,0.0,0.0,lam1+t14-EI.*lam1.*t2.*t6,t10,lam1.*t5.*t11-EI.*lam1.*t2.*t6.*t11,t2.*t5.*t10-EI.*t6.*t10.*t16,lam1.*t11,0.0,0.0,t19-EI.*t6.*t17,0.0,t13,lam2.*t5.*t12-EI.*lam2.*t6.*t7.*t12,t5.*t7.*t13-EI.*t6.*t13.*t17,lam2.*t12,0.0,0.0,0.0,lam2+t15-EI.*lam2.*t6.*t7,t12,lam2.*t5.*t13-EI.*lam2.*t6.*t7.*t13,t5.*t7.*t12-EI.*t6.*t12.*t17,lam2.*t13,0.0,0.0,0.0,0.0,-1.0,0.0,-t18+EI.*t6.*t16,0.0,t2.*t5.*t21-EI.*t6.*t16.*t21,lam1.*t22+lam1.*t5.*t22-EI.*lam1.*t2.*t6.*t22,0.0,0.0,0.0,-t14+EI.*lam1.*t2.*t6,0.0,-lam1,t2.*t5.*t22-EI.*t6.*t16.*t22,lam1.*t21+lam1.*t5.*t21-EI.*lam1.*t2.*t6.*t21,0.0,0.0,-1.0,0.0,-t19+EI.*t6.*t17,0.0,t5.*t7.*t24-EI.*t6.*t17.*t24,lam2.*t25+lam2.*t5.*t25-EI.*lam2.*t6.*t7.*t25,0.0,0.0,0.0,-t15+EI.*lam2.*t6.*t7,0.0,-lam2,t5.*t7.*t25-EI.*t6.*t17.*t25,lam2.*t24+lam2.*t5.*t24-EI.*lam2.*t6.*t7.*t24],[8,8]);
