function n = beam_righthandsidevector(EI,Mr,Vr,a,kGA,kn,qn)
%BEAM_RIGHTHANDSIDEVECTOR
%    N = BEAM_RIGHTHANDSIDEVECTOR(EI,MR,VR,A,KGA,KN,QN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2019 11:05:50

t2 = 1.0./kGA;
t3 = 1.0./EI;
n = [0.0;0.0;-qn./kn;0.0;0.0;-qn.*t2;-Mr.*t3+qn.*t2+a.^2.*qn.*t3.*(1.0./2.0);Vr.*t2+a.*qn.*t2];
