function M = beam_coefficientmatrix(EI,a,kGA,kn,ks,l,lam1,lam2)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(EI,A,KGA,KN,KS,L,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2019 11:05:50

t2 = 1.0./kGA;
t3 = lam1.^2;
t4 = lam2.^2;
t5 = 1.0./kGA.^2;
t6 = EI.*kn.*t5;
t7 = t6-1.0;
t8 = ks.*t2;
t9 = t8+1.0;
t10 = t3-t4;
t11 = t7.*t10;
t12 = t3.^2;
t13 = t4.^2;
t14 = t12+t13-t3.*t4.*6.0;
t15 = t11-EI.*t2.*t9.*t14;
t16 = lam1.*lam2.*t7.*2.0;
t17 = lam1.*lam2.*t3.*4.0;
t18 = lam1.*t7;
t19 = lam1.*t3;
t20 = lam2.*t7;
t21 = lam2.*t3.*3.0;
t22 = t21-lam2.*t4;
t23 = lam2+t20-EI.*t2.*t9.*t22;
t24 = a-l;
t27 = lam1.*t24;
t25 = exp(-t27);
t26 = lam2.*t24;
t28 = cos(t26);
t29 = exp(t27);
t30 = sin(t26);
t31 = lam1.*t25.*t28;
t32 = lam2.*t25.*t30;
t33 = t31+t32;
t34 = lam2.*t25.*t28;
t35 = t34-lam1.*t25.*t30;
t36 = lam2.*t29.*t30;
t37 = lam2.*t28.*t29;
t38 = lam1.*t29.*t30;
t39 = t37+t38;
t40 = EI.*t2.*6.0;
M = reshape([t15,lam1+t18-EI.*t2.*t9.*(t19-lam1.*t4.*3.0),t25.*t28,t33,t7.*t33-EI.*t2.*t9.*(lam1.*t3.*t25.*t28-lam1.*t4.*t25.*t28.*3.0+lam2.*t3.*t25.*t30.*3.0-lam2.*t4.*t25.*t30),t7.*(t3.*t25.*t28-t4.*t25.*t28+lam1.*lam2.*t25.*t30.*2.0)-EI.*t2.*t9.*(t12.*t25.*t28+t13.*t25.*t28-t3.*t4.*t25.*t28.*6.0+lam1.*lam2.*t3.*t25.*t30.*4.0-lam1.*lam2.*t4.*t25.*t30.*4.0),0.0,0.0,t16-EI.*t2.*t9.*(t17-lam1.*lam2.*t4.*4.0),t23,-t25.*t30,t35,t7.*t35-EI.*t2.*t9.*(lam2.*t3.*t25.*t28.*3.0-lam1.*t3.*t25.*t30-lam2.*t4.*t25.*t28+lam1.*t4.*t25.*t30.*3.0),t7.*(-t3.*t25.*t30+t4.*t25.*t30+lam1.*lam2.*t25.*t28.*2.0)+EI.*t2.*t9.*(t12.*t25.*t30+t13.*t25.*t30-t3.*t4.*t25.*t30.*6.0-lam1.*lam2.*t3.*t25.*t28.*4.0+lam1.*lam2.*t4.*t25.*t28.*4.0),0.0,0.0,t15,-lam1-t18+EI.*t2.*t9.*(t19-lam1.*t4.*3.0),t28.*t29,t36-lam1.*t28.*t29,t7.*(t36-lam1.*t28.*t29)+EI.*t2.*t9.*(lam1.*t3.*t28.*t29-lam1.*t4.*t28.*t29.*3.0-lam2.*t3.*t29.*t30.*3.0+lam2.*t4.*t29.*t30),-t7.*(-t3.*t28.*t29+t4.*t28.*t29+lam1.*lam2.*t29.*t30.*2.0)-EI.*t2.*t9.*(t12.*t28.*t29+t13.*t28.*t29-t3.*t4.*t28.*t29.*6.0-lam1.*lam2.*t3.*t29.*t30.*4.0+lam1.*lam2.*t4.*t29.*t30.*4.0),0.0,0.0,-t16+EI.*t2.*t9.*(t17-lam1.*lam2.*t4.*4.0),t23,-t29.*t30,t39,t7.*t39-EI.*t2.*t9.*(lam2.*t3.*t28.*t29.*3.0+lam1.*t3.*t29.*t30-lam2.*t4.*t28.*t29-lam1.*t4.*t29.*t30.*3.0),-t7.*(t3.*t29.*t30-t4.*t29.*t30+lam1.*lam2.*t28.*t29.*2.0)+EI.*t2.*t9.*(t12.*t29.*t30+t13.*t29.*t30-t3.*t4.*t29.*t30.*6.0+lam1.*lam2.*t3.*t28.*t29.*4.0-lam1.*lam2.*t4.*t28.*t29.*4.0),0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,-2.0,0.0,0.0,0.0,0.0,0.0,t40,0.0,a.*-6.0,-t40],[8,8]);
