function W = deflection(x,c1,c2,c3,c4,c13,c14,c15,c16,kn,l,l1,lam,qn)
%DEFLECTION
%    W = DEFLECTION(X,C1,C2,C3,C4,C13,C14,C15,C16,KN,L,L1,LAM,QN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:47

if ((x <= l1) & (0.0 <= x))
    W = exp(lam.*x).*(c1.*cos(lam.*x)+c2.*sin(lam.*x))+exp(-lam.*x).*(c3.*cos(lam.*x)+c4.*sin(lam.*x))+qn./kn;
elseif ((l1 < x) & (x <= l))
    W = qn./kn+exp(-lam.*(l1-x)).*(c13.*cos(lam.*(l1-x))-c14.*sin(lam.*(l1-x)))+exp(lam.*(l1-x)).*(c15.*cos(lam.*(l1-x))-c16.*sin(lam.*(l1-x)));
else
    W = 0.0;
end
