function n = beam_righthandsidevector(EI,Mr,Vr,a,kn,qn)
%BEAM_RIGHTHANDSIDEVECTOR
%    N = BEAM_RIGHTHANDSIDEVECTOR(EI,MR,VR,A,KN,QN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:49

t2 = 1.0./EI;
n = [0.0;0.0;-qn./kn;0.0;0.0;0.0;-Mr.*t2-a.^2.*qn.*t2.*(1.0./2.0);-Vr.*t2-a.*qn.*t2];
