function M = beam_coefficientmatrix(EI,a,kGA,kn,l,lam1,lam2)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(EI,A,KGA,KN,L,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Feb-2019 15:25:09

t2 = lam1.^2;
t3 = 1.0./kGA.^2;
t4 = EI.*kn.*t3;
t5 = t4-1.0;
t6 = 1.0./kGA;
t7 = lam2.^2;
t8 = a-l;
t9 = lam1.*t8;
t10 = lam2.*t8;
t11 = sinh(t9);
t12 = cosh(t9);
t13 = sinh(t10);
t14 = cosh(t10);
t15 = t2.^2;
t16 = t7.^2;
t17 = EI.*t6.*6.0;
M = reshape([t2.*t5-EI.*t6.*t15,0.0,t12,-lam1.*t11,-lam1.*t5.*t11+EI.*lam1.*t2.*t6.*t11,t2.*t5.*t12-EI.*t6.*t12.*t15,0.0,0.0,0.0,lam1+lam1.*t5-EI.*lam1.*t2.*t6,-t11,lam1.*t12,lam1.*t5.*t12-EI.*lam1.*t2.*t6.*t12,-t2.*t5.*t11+EI.*t6.*t11.*t15,0.0,0.0,t5.*t7-EI.*t6.*t16,0.0,t14,-lam2.*t13,-lam2.*t5.*t13+EI.*lam2.*t6.*t7.*t13,t5.*t7.*t14-EI.*t6.*t14.*t16,0.0,0.0,0.0,lam2+lam2.*t5-EI.*lam2.*t6.*t7,-t13,lam2.*t14,lam2.*t5.*t14-EI.*lam2.*t6.*t7.*t14,-t5.*t7.*t13+EI.*t6.*t13.*t16,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,-2.0,0.0,0.0,0.0,0.0,0.0,t17,0.0,a.*-6.0,-t17],[8,8]);
