function W = deflection(x,c1,c2,c3,c4,c13,c14,c15,c16,kn,l,l1,lam1,lam2,qn)
%DEFLECTION
%    W = DEFLECTION(X,C1,C2,C3,C4,C13,C14,C15,C16,KN,L,L1,LAM1,LAM2,QN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Feb-2019 15:25:03

if ((x <= l1) & (0.0 <= x))
    W = exp(lam1.*x).*(c1.*cos(lam2.*x)+c2.*sin(lam2.*x))+exp(-lam1.*x).*(c3.*cos(lam2.*x)+c4.*sin(lam2.*x))+qn./kn;
elseif ((l1 < x) & (x <= l))
    W = qn./kn+exp(-lam1.*(l1-x)).*(c13.*cos(lam2.*(l1-x))-c14.*sin(lam2.*(l1-x)))+exp(lam1.*(l1-x)).*(c15.*cos(lam2.*(l1-x))-c16.*sin(lam2.*(l1-x)));
else
    W = 0.0;
end
