function n = beam_righthandsidevector(EI,Fn)
%BEAM_RIGHTHANDSIDEVECTOR
%    N = BEAM_RIGHTHANDSIDEVECTOR(EI,FN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:47

n = [0.0;0.0;0.0;0.0;0.0;-Fn./EI;0.0;0.0];
