function M = beam_coefficientmatrix(EI,a,kGA,kn,l,lam1,lam2)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(EI,A,KGA,KN,L,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Feb-2019 15:25:06

t2 = lam1.^2;
t3 = lam2.^2;
t4 = 1.0./kGA.^2;
t5 = EI.*kn.*t4;
t6 = t5-1.0;
t7 = 1.0./kGA;
t8 = t2-t3;
t9 = t6.*t8;
t10 = t2.^2;
t11 = t3.^2;
t12 = t10+t11-t2.*t3.*6.0;
t13 = t9-EI.*t7.*t12;
t14 = lam1.*lam2.*t6.*2.0;
t15 = lam1.*lam2.*t2.*4.0;
t16 = lam1.*t6;
t17 = lam1.*t2;
t18 = lam2.*t6;
t19 = lam2.*t2.*3.0;
t20 = t19-lam2.*t3;
t21 = lam2+t18-EI.*t7.*t20;
t22 = a-l;
t25 = lam1.*t22;
t23 = exp(-t25);
t24 = lam2.*t22;
t26 = cos(t24);
t27 = exp(t25);
t28 = sin(t24);
t29 = lam1.*t23.*t26;
t30 = lam2.*t23.*t28;
t31 = t29+t30;
t32 = lam2.*t23.*t26;
t33 = t32-lam1.*t23.*t28;
t34 = lam2.*t27.*t28;
t35 = lam2.*t26.*t27;
t36 = lam1.*t27.*t28;
t37 = t35+t36;
t38 = EI.*t7.*6.0;
M = reshape([t13,lam1+t16-EI.*t7.*(t17-lam1.*t3.*3.0),t23.*t26,t31,t6.*t31-EI.*t7.*(lam1.*t2.*t23.*t26-lam1.*t3.*t23.*t26.*3.0+lam2.*t2.*t23.*t28.*3.0-lam2.*t3.*t23.*t28),t6.*(t2.*t23.*t26-t3.*t23.*t26+lam1.*lam2.*t23.*t28.*2.0)-EI.*t7.*(t10.*t23.*t26+t11.*t23.*t26-t2.*t3.*t23.*t26.*6.0+lam1.*lam2.*t2.*t23.*t28.*4.0-lam1.*lam2.*t3.*t23.*t28.*4.0),0.0,0.0,t14-EI.*t7.*(t15-lam1.*lam2.*t3.*4.0),t21,-t23.*t28,t33,t6.*t33-EI.*t7.*(lam2.*t2.*t23.*t26.*3.0-lam1.*t2.*t23.*t28-lam2.*t3.*t23.*t26+lam1.*t3.*t23.*t28.*3.0),t6.*(-t2.*t23.*t28+t3.*t23.*t28+lam1.*lam2.*t23.*t26.*2.0)+EI.*t7.*(t10.*t23.*t28+t11.*t23.*t28-t2.*t3.*t23.*t28.*6.0-lam1.*lam2.*t2.*t23.*t26.*4.0+lam1.*lam2.*t3.*t23.*t26.*4.0),0.0,0.0,t13,-lam1-t16+EI.*t7.*(t17-lam1.*t3.*3.0),t26.*t27,t34-lam1.*t26.*t27,t6.*(t34-lam1.*t26.*t27)+EI.*t7.*(lam1.*t2.*t26.*t27-lam1.*t3.*t26.*t27.*3.0-lam2.*t2.*t27.*t28.*3.0+lam2.*t3.*t27.*t28),-t6.*(-t2.*t26.*t27+t3.*t26.*t27+lam1.*lam2.*t27.*t28.*2.0)-EI.*t7.*(t10.*t26.*t27+t11.*t26.*t27-t2.*t3.*t26.*t27.*6.0-lam1.*lam2.*t2.*t27.*t28.*4.0+lam1.*lam2.*t3.*t27.*t28.*4.0),0.0,0.0,-t14+EI.*t7.*(t15-lam1.*lam2.*t3.*4.0),t21,-t27.*t28,t37,t6.*t37-EI.*t7.*(lam2.*t2.*t26.*t27.*3.0+lam1.*t2.*t27.*t28-lam2.*t3.*t26.*t27-lam1.*t3.*t27.*t28.*3.0),-t6.*(t2.*t27.*t28-t3.*t27.*t28+lam1.*lam2.*t26.*t27.*2.0)+EI.*t7.*(t10.*t27.*t28+t11.*t27.*t28-t2.*t3.*t27.*t28.*6.0+lam1.*lam2.*t2.*t26.*t27.*4.0-lam1.*lam2.*t3.*t26.*t27.*4.0),0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,-2.0,0.0,0.0,0.0,0.0,0.0,t38,0.0,a.*-6.0,-t38],[8,8]);
