function d = rod_righthandsidevector(EA,Ft)
%ROD_RIGHTHANDSIDEVECTOR
%    D = ROD_RIGHTHANDSIDEVECTOR(EA,FT)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:49

d = [0.0;0.0;Ft./EA;0.0];
