function n = beam_righthandsidevector(Fn,kGA)
%BEAM_RIGHTHANDSIDEVECTOR
%    N = BEAM_RIGHTHANDSIDEVECTOR(FN,KGA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Feb-2019 15:25:03

n = [0.0;0.0;0.0;0.0;0.0;Fn./kGA;0.0;0.0];
