function M = beam_coefficientmatrix(EI,a,kGA,kn,ks,l,lam1,lam2)
%BEAM_COEFFICIENTMATRIX
%    M = BEAM_COEFFICIENTMATRIX(EI,A,KGA,KN,KS,L,LAM1,LAM2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2019 11:05:54

t2 = lam1.^2;
t3 = 1.0./kGA;
t4 = 1.0./kGA.^2;
t5 = EI.*kn.*t4;
t6 = t5-1.0;
t7 = lam2.^2;
t8 = ks.*t3;
t9 = t8+1.0;
t10 = a-l;
t11 = lam1.*t10;
t12 = lam2.*t10;
t13 = sinh(t11);
t14 = cosh(t11);
t15 = sinh(t12);
t16 = cosh(t12);
t17 = t2.^2;
t18 = t7.^2;
t19 = EI.*t3.*6.0;
M = reshape([t2.*t6-EI.*t3.*t9.*t17,0.0,t14,-lam1.*t13,-lam1.*t6.*t13+EI.*lam1.*t2.*t3.*t9.*t13,t2.*t6.*t14-EI.*t3.*t9.*t14.*t17,0.0,0.0,0.0,lam1+lam1.*t6-EI.*lam1.*t2.*t3.*t9,-t13,lam1.*t14,lam1.*t6.*t14-EI.*lam1.*t2.*t3.*t9.*t14,-t2.*t6.*t13+EI.*t3.*t9.*t13.*t17,0.0,0.0,t6.*t7-EI.*t3.*t9.*t18,0.0,t16,-lam2.*t15,-lam2.*t6.*t15+EI.*lam2.*t3.*t7.*t9.*t15,t6.*t7.*t16-EI.*t3.*t9.*t16.*t18,0.0,0.0,0.0,lam2+lam2.*t6-EI.*lam2.*t3.*t7.*t9,-t15,lam2.*t16,lam2.*t6.*t16-EI.*lam2.*t3.*t7.*t9.*t16,-t6.*t7.*t15+EI.*t3.*t9.*t15.*t18,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,-2.0,0.0,0.0,0.0,0.0,0.0,t19,0.0,a.*-6.0,-t19],[8,8]);
