function Wp = inclination(x,EI,a,c1,c2,c3,c4,c6,c7,c8,l,lam1,lam2,qn)
%INCLINATION
%    WP = INCLINATION(X,EI,A,C1,C2,C3,C4,C6,C7,C8,L,LAM1,LAM2,QN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Feb-2019 11:05:54

if ((a+x <= l) & (0.0 <= x))
    Wp = c2.*lam1.*cosh(lam1.*x)+c4.*lam2.*cosh(lam2.*x)+c1.*lam1.*sinh(lam1.*x)+c3.*lam2.*sinh(lam2.*x);
elseif ((l < a+x) & (x <= l))
    Wp = c6+c8.*(a-l+x).^2.*3.0+c7.*(a-l+x).*2.0+(qn.*(a-l+x).^3.*(1.0./6.0))./EI;
else
    Wp = 0.0;
end
