function n = beam_righthandsidevector(EI,Fn,kn,l2,l3,qn)
%BEAM_RIGHTHANDSIDEVECTOR
%    N = BEAM_RIGHTHANDSIDEVECTOR(EI,FN,KN,L2,L3,QN)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-Mar-2019 00:54:48

t2 = l2.^2;
t3 = 1.0./EI;
t4 = 1.0./kn;
t5 = l3.^2;
n = [0.0;0.0;-qn.*t4;0.0;0.0;0.0;qn.*t2.^2.*t3.*(-1.0./2.4e1);l2.*qn.*t2.*t3.*(-1.0./6.0);qn.*t2.*t3.*(-1.0./2.0);-Fn.*t3-l2.*qn.*t3;qn.*t4-qn.*t3.*t5.^2.*(1.0./2.4e1);l3.*qn.*t3.*t5.*(-1.0./6.0);qn.*t3.*t5.*(-1.0./2.0);-l3.*qn.*t3;0.0;0.0];
